name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-report
        path: bandit-report.json

  dast_scan:
    name: Run ZAP Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start PyGoat
      run: |
        pip install -r requirements.txt
        python3 manage.py migrate
        python3 manage.py runserver &

    - name: ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.13.0
      with:
        target: http://127.0.0.1:8000

  image_scan:
    name: Build Image and run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: 'latest'

    - name: Build Docker Image
      run: |
        docker build -f Dockerfile -t myapp:latest .

    - name: Docker Scout Scan
      uses: docker/scout-action@v1.15.0
      with:
        dockerhub-user: ${{ secrets.DOCKER_USER }}
        dockerhub-password: ${{ secrets.DOCKER_PASS }}
        command: quickview, cves
        only-severities: critical,high
        sarif-file: scout-report.sarif
